/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_ATTEST_DASHALTERNATIVE_COLON = 1,
  anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON = 2,
  anon_sym_ATTEST_DASHDOC_COLON = 3,
  anon_sym_ATTEST_DASHEXEC_COLON = 4,
  anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON = 5,
  anon_sym_ATTEST_DASHGROUP_COLON = 6,
  sym_ignore = 7,
  sym_measure_time = 8,
  anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON = 9,
  anon_sym_ATTEST_DASHPORT_COLON = 10,
  anon_sym_ATTEST_DASHREQUIRES_COLON = 11,
  anon_sym_ATTEST_DASHSERIALIZE_COLON = 12,
  anon_sym_ATTEST_DASHSTART_DASHNEXT = 13,
  anon_sym_ATTEST_DASHSTART_DASHFILE = 14,
  sym_end_file = 15,
  aux_sym_sh_token1 = 16,
  sym_comment = 17,
  sym_literal_file = 18,
  sym_error_sentinel = 19,
  sym_source_file = 20,
  sym_alternative = 21,
  sym_copy_file = 22,
  sym_doc = 23,
  sym_exec = 24,
  sym_exec_fail = 25,
  sym_group = 26,
  sym_not_alternative = 27,
  sym_port = 28,
  sym_requires = 29,
  sym_serialize = 30,
  sym_start_next = 31,
  sym_start_file = 32,
  sym_sh = 33,
  sym_string = 34,
  aux_sym_source_file_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = "@TEST-ALTERNATIVE:",
  [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = "@TEST-COPY-FILE:",
  [anon_sym_ATTEST_DASHDOC_COLON] = "@TEST-DOC:",
  [anon_sym_ATTEST_DASHEXEC_COLON] = "@TEST-EXEC:",
  [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = "@TEST-EXEC-FAIL:",
  [anon_sym_ATTEST_DASHGROUP_COLON] = "@TEST-GROUP:",
  [sym_ignore] = "ignore",
  [sym_measure_time] = "measure_time",
  [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = "@TEST-NOT-ALTERNATIVE:",
  [anon_sym_ATTEST_DASHPORT_COLON] = "@TEST-PORT:",
  [anon_sym_ATTEST_DASHREQUIRES_COLON] = "@TEST-REQUIRES:",
  [anon_sym_ATTEST_DASHSERIALIZE_COLON] = "@TEST-SERIALIZE:",
  [anon_sym_ATTEST_DASHSTART_DASHNEXT] = "@TEST-START-NEXT",
  [anon_sym_ATTEST_DASHSTART_DASHFILE] = "@TEST-START-FILE",
  [sym_end_file] = "end_file",
  [aux_sym_sh_token1] = "sh_token1",
  [sym_comment] = "comment",
  [sym_literal_file] = "literal_file",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym_alternative] = "alternative",
  [sym_copy_file] = "copy_file",
  [sym_doc] = "doc",
  [sym_exec] = "exec",
  [sym_exec_fail] = "exec_fail",
  [sym_group] = "group",
  [sym_not_alternative] = "not_alternative",
  [sym_port] = "port",
  [sym_requires] = "requires",
  [sym_serialize] = "serialize",
  [sym_start_next] = "start_next",
  [sym_start_file] = "start_file",
  [sym_sh] = "sh",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = anon_sym_ATTEST_DASHALTERNATIVE_COLON,
  [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
  [anon_sym_ATTEST_DASHDOC_COLON] = anon_sym_ATTEST_DASHDOC_COLON,
  [anon_sym_ATTEST_DASHEXEC_COLON] = anon_sym_ATTEST_DASHEXEC_COLON,
  [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
  [anon_sym_ATTEST_DASHGROUP_COLON] = anon_sym_ATTEST_DASHGROUP_COLON,
  [sym_ignore] = sym_ignore,
  [sym_measure_time] = sym_measure_time,
  [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
  [anon_sym_ATTEST_DASHPORT_COLON] = anon_sym_ATTEST_DASHPORT_COLON,
  [anon_sym_ATTEST_DASHREQUIRES_COLON] = anon_sym_ATTEST_DASHREQUIRES_COLON,
  [anon_sym_ATTEST_DASHSERIALIZE_COLON] = anon_sym_ATTEST_DASHSERIALIZE_COLON,
  [anon_sym_ATTEST_DASHSTART_DASHNEXT] = anon_sym_ATTEST_DASHSTART_DASHNEXT,
  [anon_sym_ATTEST_DASHSTART_DASHFILE] = anon_sym_ATTEST_DASHSTART_DASHFILE,
  [sym_end_file] = sym_end_file,
  [aux_sym_sh_token1] = aux_sym_sh_token1,
  [sym_comment] = sym_comment,
  [sym_literal_file] = sym_literal_file,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_alternative] = sym_alternative,
  [sym_copy_file] = sym_copy_file,
  [sym_doc] = sym_doc,
  [sym_exec] = sym_exec,
  [sym_exec_fail] = sym_exec_fail,
  [sym_group] = sym_group,
  [sym_not_alternative] = sym_not_alternative,
  [sym_port] = sym_port,
  [sym_requires] = sym_requires,
  [sym_serialize] = sym_serialize,
  [sym_start_next] = sym_start_next,
  [sym_start_file] = sym_start_file,
  [sym_sh] = sym_sh,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHDOC_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHEXEC_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHGROUP_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_ignore] = {
    .visible = true,
    .named = true,
  },
  [sym_measure_time] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHPORT_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHREQUIRES_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHSERIALIZE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHSTART_DASHNEXT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATTEST_DASHSTART_DASHFILE] = {
    .visible = true,
    .named = false,
  },
  [sym_end_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_sh_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_file] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_copy_file] = {
    .visible = true,
    .named = true,
  },
  [sym_doc] = {
    .visible = true,
    .named = true,
  },
  [sym_exec] = {
    .visible = true,
    .named = true,
  },
  [sym_exec_fail] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_not_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_port] = {
    .visible = true,
    .named = true,
  },
  [sym_requires] = {
    .visible = true,
    .named = true,
  },
  [sym_serialize] = {
    .visible = true,
    .named = true,
  },
  [sym_start_next] = {
    .visible = true,
    .named = true,
  },
  [sym_start_file] = {
    .visible = true,
    .named = true,
  },
  [sym_sh] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(115);
      if (lookahead == '#') ADVANCE(134);
      if (lookahead == '@') ADVANCE(93);
      if (lookahead == '\\') SKIP(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(48);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == ':') ADVANCE(119);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(118);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(125);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(121);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(126);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(117);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(120);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(127);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(116);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(124);
      END_STATE();
    case 16:
      ADVANCE_MAP(
        'A', 65,
        'C', 72,
        'D', 73,
        'E', 68,
        'G', 84,
        'I', 49,
        'M', 28,
        'N', 76,
        'P', 75,
        'R', 29,
        'S', 38,
      );
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(91);
      END_STATE();
    case 18:
      if (lookahead == 'A') ADVANCE(60);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(100);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'A') ADVANCE(88);
      END_STATE();
    case 22:
      if (lookahead == 'A') ADVANCE(102);
      END_STATE();
    case 23:
      if (lookahead == 'A') ADVANCE(66);
      END_STATE();
    case 24:
      if (lookahead == 'C') ADVANCE(7);
      END_STATE();
    case 25:
      if (lookahead == 'C') ADVANCE(4);
      END_STATE();
    case 26:
      if (lookahead == 'D') ADVANCE(2);
      END_STATE();
    case 27:
      if (lookahead == 'E') ADVANCE(90);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(80);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(122);
      END_STATE();
    case 31:
      if (lookahead == 'E') ADVANCE(112);
      END_STATE();
    case 32:
      if (lookahead == 'E') ADVANCE(130);
      END_STATE();
    case 33:
      if (lookahead == 'E') ADVANCE(109);
      END_STATE();
    case 34:
      if (lookahead == 'E') ADVANCE(129);
      END_STATE();
    case 35:
      if (lookahead == 'E') ADVANCE(123);
      END_STATE();
    case 36:
      if (lookahead == 'E') ADVANCE(25);
      END_STATE();
    case 37:
      if (lookahead == 'E') ADVANCE(92);
      END_STATE();
    case 38:
      if (lookahead == 'E') ADVANCE(81);
      if (lookahead == 'T') ADVANCE(21);
      END_STATE();
    case 39:
      if (lookahead == 'E') ADVANCE(82);
      END_STATE();
    case 40:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 41:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 42:
      if (lookahead == 'E') ADVANCE(14);
      END_STATE();
    case 43:
      if (lookahead == 'E') ADVANCE(15);
      END_STATE();
    case 44:
      if (lookahead == 'E') ADVANCE(89);
      END_STATE();
    case 45:
      if (lookahead == 'F') ADVANCE(53);
      END_STATE();
    case 46:
      if (lookahead == 'F') ADVANCE(20);
      END_STATE();
    case 47:
      if (lookahead == 'F') ADVANCE(58);
      END_STATE();
    case 48:
      if (lookahead == 'F') ADVANCE(59);
      if (lookahead == 'N') ADVANCE(33);
      END_STATE();
    case 49:
      if (lookahead == 'G') ADVANCE(70);
      END_STATE();
    case 50:
      if (lookahead == 'I') ADVANCE(111);
      END_STATE();
    case 51:
      if (lookahead == 'I') ADVANCE(107);
      END_STATE();
    case 52:
      if (lookahead == 'I') ADVANCE(67);
      END_STATE();
    case 53:
      if (lookahead == 'I') ADVANCE(62);
      END_STATE();
    case 54:
      if (lookahead == 'I') ADVANCE(61);
      END_STATE();
    case 55:
      if (lookahead == 'I') ADVANCE(18);
      END_STATE();
    case 56:
      if (lookahead == 'I') ADVANCE(87);
      END_STATE();
    case 57:
      if (lookahead == 'I') ADVANCE(108);
      END_STATE();
    case 58:
      if (lookahead == 'I') ADVANCE(63);
      END_STATE();
    case 59:
      if (lookahead == 'I') ADVANCE(64);
      END_STATE();
    case 60:
      if (lookahead == 'L') ADVANCE(50);
      END_STATE();
    case 61:
      if (lookahead == 'L') ADVANCE(12);
      END_STATE();
    case 62:
      if (lookahead == 'L') ADVANCE(32);
      END_STATE();
    case 63:
      if (lookahead == 'L') ADVANCE(40);
      END_STATE();
    case 64:
      if (lookahead == 'L') ADVANCE(34);
      END_STATE();
    case 65:
      if (lookahead == 'L') ADVANCE(99);
      END_STATE();
    case 66:
      if (lookahead == 'L') ADVANCE(103);
      END_STATE();
    case 67:
      if (lookahead == 'M') ADVANCE(35);
      END_STATE();
    case 68:
      if (lookahead == 'N') ADVANCE(26);
      if (lookahead == 'X') ADVANCE(36);
      END_STATE();
    case 69:
      if (lookahead == 'N') ADVANCE(19);
      END_STATE();
    case 70:
      if (lookahead == 'N') ADVANCE(77);
      END_STATE();
    case 71:
      if (lookahead == 'N') ADVANCE(22);
      END_STATE();
    case 72:
      if (lookahead == 'O') ADVANCE(78);
      END_STATE();
    case 73:
      if (lookahead == 'O') ADVANCE(24);
      END_STATE();
    case 74:
      if (lookahead == 'O') ADVANCE(104);
      END_STATE();
    case 75:
      if (lookahead == 'O') ADVANCE(83);
      END_STATE();
    case 76:
      if (lookahead == 'O') ADVANCE(97);
      END_STATE();
    case 77:
      if (lookahead == 'O') ADVANCE(85);
      END_STATE();
    case 78:
      if (lookahead == 'P') ADVANCE(110);
      END_STATE();
    case 79:
      if (lookahead == 'P') ADVANCE(9);
      END_STATE();
    case 80:
      if (lookahead == 'Q') ADVANCE(105);
      END_STATE();
    case 81:
      if (lookahead == 'R') ADVANCE(55);
      END_STATE();
    case 82:
      if (lookahead == 'R') ADVANCE(69);
      END_STATE();
    case 83:
      if (lookahead == 'R') ADVANCE(96);
      END_STATE();
    case 84:
      if (lookahead == 'R') ADVANCE(74);
      END_STATE();
    case 85:
      if (lookahead == 'R') ADVANCE(30);
      END_STATE();
    case 86:
      if (lookahead == 'R') ADVANCE(31);
      END_STATE();
    case 87:
      if (lookahead == 'R') ADVANCE(37);
      END_STATE();
    case 88:
      if (lookahead == 'R') ADVANCE(98);
      END_STATE();
    case 89:
      if (lookahead == 'R') ADVANCE(71);
      END_STATE();
    case 90:
      if (lookahead == 'S') ADVANCE(94);
      END_STATE();
    case 91:
      if (lookahead == 'S') ADVANCE(106);
      END_STATE();
    case 92:
      if (lookahead == 'S') ADVANCE(10);
      END_STATE();
    case 93:
      if (lookahead == 'T') ADVANCE(27);
      END_STATE();
    case 94:
      if (lookahead == 'T') ADVANCE(1);
      END_STATE();
    case 95:
      if (lookahead == 'T') ADVANCE(128);
      END_STATE();
    case 96:
      if (lookahead == 'T') ADVANCE(8);
      END_STATE();
    case 97:
      if (lookahead == 'T') ADVANCE(5);
      END_STATE();
    case 98:
      if (lookahead == 'T') ADVANCE(3);
      END_STATE();
    case 99:
      if (lookahead == 'T') ADVANCE(39);
      END_STATE();
    case 100:
      if (lookahead == 'T') ADVANCE(51);
      END_STATE();
    case 101:
      if (lookahead == 'T') ADVANCE(52);
      END_STATE();
    case 102:
      if (lookahead == 'T') ADVANCE(57);
      END_STATE();
    case 103:
      if (lookahead == 'T') ADVANCE(44);
      END_STATE();
    case 104:
      if (lookahead == 'U') ADVANCE(79);
      END_STATE();
    case 105:
      if (lookahead == 'U') ADVANCE(56);
      END_STATE();
    case 106:
      if (lookahead == 'U') ADVANCE(86);
      END_STATE();
    case 107:
      if (lookahead == 'V') ADVANCE(42);
      END_STATE();
    case 108:
      if (lookahead == 'V') ADVANCE(43);
      END_STATE();
    case 109:
      if (lookahead == 'X') ADVANCE(95);
      END_STATE();
    case 110:
      if (lookahead == 'Y') ADVANCE(6);
      END_STATE();
    case 111:
      if (lookahead == 'Z') ADVANCE(41);
      END_STATE();
    case 112:
      if (lookahead == '_') ADVANCE(101);
      END_STATE();
    case 113:
      if (eof) ADVANCE(115);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 114:
      if (eof) ADVANCE(115);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(113);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHALTERNATIVE_COLON);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHDOC_COLON);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHEXEC_COLON);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHGROUP_COLON);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_ignore);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_measure_time);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHPORT_COLON);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHREQUIRES_COLON);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHSERIALIZE_COLON);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHSTART_DASHNEXT);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_ATTEST_DASHSTART_DASHFILE);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_end_file);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_sh_token1);
      ADVANCE_MAP(
        '#', 132,
        '\\', 133,
        '\t', 131,
        0x0b, 131,
        '\f', 131,
        ' ', 131,
        0x200b, 131,
        0x2060, 131,
        0xfeff, 131,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(133);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_sh_token1);
      if (lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_sh_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(134);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 131},
  [19] = {.lex_state = 131},
  [20] = {.lex_state = 131},
  [21] = {.lex_state = 131},
  [22] = {.lex_state = 131},
  [23] = {.lex_state = 131},
  [24] = {.lex_state = 131},
  [25] = {.lex_state = 131},
  [26] = {.lex_state = 131},
  [27] = {.lex_state = 131},
  [28] = {.lex_state = 131},
  [29] = {.lex_state = 131},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHDOC_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHEXEC_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHGROUP_COLON] = ACTIONS(1),
    [sym_ignore] = ACTIONS(1),
    [sym_measure_time] = ACTIONS(1),
    [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHPORT_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHREQUIRES_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHSERIALIZE_COLON] = ACTIONS(1),
    [anon_sym_ATTEST_DASHSTART_DASHNEXT] = ACTIONS(1),
    [anon_sym_ATTEST_DASHSTART_DASHFILE] = ACTIONS(1),
    [sym_end_file] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_literal_file] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym_alternative] = STATE(2),
    [sym_copy_file] = STATE(2),
    [sym_doc] = STATE(2),
    [sym_exec] = STATE(2),
    [sym_exec_fail] = STATE(2),
    [sym_group] = STATE(2),
    [sym_not_alternative] = STATE(2),
    [sym_port] = STATE(2),
    [sym_requires] = STATE(2),
    [sym_serialize] = STATE(2),
    [sym_start_next] = STATE(2),
    [sym_start_file] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = ACTIONS(7),
    [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = ACTIONS(9),
    [anon_sym_ATTEST_DASHDOC_COLON] = ACTIONS(11),
    [anon_sym_ATTEST_DASHEXEC_COLON] = ACTIONS(13),
    [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = ACTIONS(15),
    [anon_sym_ATTEST_DASHGROUP_COLON] = ACTIONS(17),
    [sym_ignore] = ACTIONS(19),
    [sym_measure_time] = ACTIONS(19),
    [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = ACTIONS(21),
    [anon_sym_ATTEST_DASHPORT_COLON] = ACTIONS(23),
    [anon_sym_ATTEST_DASHREQUIRES_COLON] = ACTIONS(25),
    [anon_sym_ATTEST_DASHSERIALIZE_COLON] = ACTIONS(27),
    [anon_sym_ATTEST_DASHSTART_DASHNEXT] = ACTIONS(29),
    [anon_sym_ATTEST_DASHSTART_DASHFILE] = ACTIONS(31),
    [sym_end_file] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_alternative] = STATE(3),
    [sym_copy_file] = STATE(3),
    [sym_doc] = STATE(3),
    [sym_exec] = STATE(3),
    [sym_exec_fail] = STATE(3),
    [sym_group] = STATE(3),
    [sym_not_alternative] = STATE(3),
    [sym_port] = STATE(3),
    [sym_requires] = STATE(3),
    [sym_serialize] = STATE(3),
    [sym_start_next] = STATE(3),
    [sym_start_file] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = ACTIONS(7),
    [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = ACTIONS(9),
    [anon_sym_ATTEST_DASHDOC_COLON] = ACTIONS(11),
    [anon_sym_ATTEST_DASHEXEC_COLON] = ACTIONS(13),
    [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = ACTIONS(15),
    [anon_sym_ATTEST_DASHGROUP_COLON] = ACTIONS(17),
    [sym_ignore] = ACTIONS(35),
    [sym_measure_time] = ACTIONS(35),
    [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = ACTIONS(21),
    [anon_sym_ATTEST_DASHPORT_COLON] = ACTIONS(23),
    [anon_sym_ATTEST_DASHREQUIRES_COLON] = ACTIONS(25),
    [anon_sym_ATTEST_DASHSERIALIZE_COLON] = ACTIONS(27),
    [anon_sym_ATTEST_DASHSTART_DASHNEXT] = ACTIONS(29),
    [anon_sym_ATTEST_DASHSTART_DASHFILE] = ACTIONS(31),
    [sym_end_file] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_alternative] = STATE(3),
    [sym_copy_file] = STATE(3),
    [sym_doc] = STATE(3),
    [sym_exec] = STATE(3),
    [sym_exec_fail] = STATE(3),
    [sym_group] = STATE(3),
    [sym_not_alternative] = STATE(3),
    [sym_port] = STATE(3),
    [sym_requires] = STATE(3),
    [sym_serialize] = STATE(3),
    [sym_start_next] = STATE(3),
    [sym_start_file] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_ATTEST_DASHALTERNATIVE_COLON] = ACTIONS(39),
    [anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON] = ACTIONS(42),
    [anon_sym_ATTEST_DASHDOC_COLON] = ACTIONS(45),
    [anon_sym_ATTEST_DASHEXEC_COLON] = ACTIONS(48),
    [anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON] = ACTIONS(51),
    [anon_sym_ATTEST_DASHGROUP_COLON] = ACTIONS(54),
    [sym_ignore] = ACTIONS(57),
    [sym_measure_time] = ACTIONS(57),
    [anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON] = ACTIONS(60),
    [anon_sym_ATTEST_DASHPORT_COLON] = ACTIONS(63),
    [anon_sym_ATTEST_DASHREQUIRES_COLON] = ACTIONS(66),
    [anon_sym_ATTEST_DASHSERIALIZE_COLON] = ACTIONS(69),
    [anon_sym_ATTEST_DASHSTART_DASHNEXT] = ACTIONS(72),
    [anon_sym_ATTEST_DASHSTART_DASHFILE] = ACTIONS(75),
    [sym_end_file] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [22] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [44] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [66] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [88] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [132] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [220] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 16,
      ts_builtin_sym_end,
      anon_sym_ATTEST_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHCOPY_DASHFILE_COLON,
      anon_sym_ATTEST_DASHDOC_COLON,
      anon_sym_ATTEST_DASHEXEC_COLON,
      anon_sym_ATTEST_DASHEXEC_DASHFAIL_COLON,
      anon_sym_ATTEST_DASHGROUP_COLON,
      sym_ignore,
      sym_measure_time,
      anon_sym_ATTEST_DASHNOT_DASHALTERNATIVE_COLON,
      anon_sym_ATTEST_DASHPORT_COLON,
      anon_sym_ATTEST_DASHREQUIRES_COLON,
      anon_sym_ATTEST_DASHSERIALIZE_COLON,
      anon_sym_ATTEST_DASHSTART_DASHNEXT,
      anon_sym_ATTEST_DASHSTART_DASHFILE,
      sym_end_file,
  [308] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(5), 1,
      sym_string,
  [318] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(6), 1,
      sym_string,
  [328] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(7), 1,
      sym_string,
  [338] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_sh_token1,
    STATE(9), 1,
      sym_sh,
  [348] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_sh_token1,
    STATE(10), 1,
      sym_sh,
  [358] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(11), 1,
      sym_string,
  [368] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(12), 1,
      sym_string,
  [378] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(13), 1,
      sym_string,
  [388] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_sh_token1,
    STATE(14), 1,
      sym_sh,
  [398] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(15), 1,
      sym_string,
  [408] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(16), 1,
      sym_string,
  [418] = 3,
    ACTIONS(106), 1,
      aux_sym_sh_token1,
    ACTIONS(108), 1,
      sym_comment,
    STATE(17), 1,
      sym_string,
  [428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 22,
  [SMALL_STATE(6)] = 44,
  [SMALL_STATE(7)] = 66,
  [SMALL_STATE(8)] = 88,
  [SMALL_STATE(9)] = 110,
  [SMALL_STATE(10)] = 132,
  [SMALL_STATE(11)] = 154,
  [SMALL_STATE(12)] = 176,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 220,
  [SMALL_STATE(15)] = 242,
  [SMALL_STATE(16)] = 264,
  [SMALL_STATE(17)] = 286,
  [SMALL_STATE(18)] = 308,
  [SMALL_STATE(19)] = 318,
  [SMALL_STATE(20)] = 328,
  [SMALL_STATE(21)] = 338,
  [SMALL_STATE(22)] = 348,
  [SMALL_STATE(23)] = 358,
  [SMALL_STATE(24)] = 368,
  [SMALL_STATE(25)] = 378,
  [SMALL_STATE(26)] = 388,
  [SMALL_STATE(27)] = 398,
  [SMALL_STATE(28)] = 408,
  [SMALL_STATE(29)] = 418,
  [SMALL_STATE(30)] = 428,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy_file, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sh, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exec, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exec_fail, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not_alternative, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_serialize, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_next, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_file, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_literal_file = 0,
  ts_external_token_error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_literal_file] = sym_literal_file,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_literal_file] = true,
    [ts_external_token_error_sentinel] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_btest_external_scanner_create(void);
void tree_sitter_btest_external_scanner_destroy(void *);
bool tree_sitter_btest_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_btest_external_scanner_serialize(void *, char *);
void tree_sitter_btest_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_btest(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_btest_external_scanner_create,
      tree_sitter_btest_external_scanner_destroy,
      tree_sitter_btest_external_scanner_scan,
      tree_sitter_btest_external_scanner_serialize,
      tree_sitter_btest_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "btest",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
